#!/usr/bin/python3

def afficher_multiplication(n, min=1, max=10):
    if min > max:
        min, max = max, min
        print("Attention : min et max ont été inversés")


    for i in range(min, max+1): #max+1 car ca affiche jms le last chiffre (exclusion)
        print(f"{n} x {i} = {n * i}")

afficher_multiplication(4, 0, 10)
